# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module
