title: Спектрум
# Include external resources
resources:
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module

####################################################
#                                                  #
#                View - Home                       #
#                                                  #
####################################################

views:
  # View tab title.
  - title: Світло
    # Optional background (overwrites the global background).

    #background: radial-gradient(crimson, skyblue)
    # Each view can have a different theme applied. Theme should be defined in the frontend.
    #theme: dark-mode
    # The cards to show on this view.

    ####################################################
    #                                                  #
    #                     Cards                        #
    #                                                  #
    ####################################################

    cards:
      - type: markdown
        content: >
          ## Увімкнене світло
      - type: custom:auto-entities
        show_empty: false
        card:
          type: entities
          show_header_toggle: false
        filter:
          include:
            - domain: switch
              state: "on"
              options:
                secondary_info: last-changed
  - title: System
    cards:
      - type: horizontal-stack
        cards:
          - type: glance
            entities:
              - sensor.cpu_temperature
          - type: glance
            show_name: false
            entities:
              - sun.sun
